### ISSUE TITLE
Support different CheckRetry per request

### ISSUE THREAD

**Issue by dmarkhas** [hashicorp/go-retryablehttp#104]
Currently, the `CheckRetry` policy is specific to the client instance and applies to all requests it makes. However, various APIs may behave differently and thus require different handling.
This forces us to create multiple client instances, each with its own `CheckRetry`. It would be better if we could reuse the same client instance, and provide a different policy per request.

**Comment by ryanuber** [comment]
Hey @dmarkhas , thanks for reporting this. Currently the supported approach if you require different retry policies is to create instances of the Client and configure the appropriate `CheckRetry` on each. This is a decent pattern, I think, as it avoids the necessity of passing in the appropriate retry policy on every request, requiring you to configure it only once, and then use the pre-configured client wherever it is needed.

At this time we're not planning support for a per-request retry policy for the reasons above. Thank you for the suggestion, though!
