### ISSUE TITLE
How to use go-retryablehttp with a Client with a custom Transport?

### ISSUE THREAD

**Issue by tekchain** [hashicorp/go-retryablehttp#119]
Dear Hashicorp team,

Is it possible to use go-retryablehttp with a Client with a custom Transport?

Thanks,

Daniel

**Comment by jefferai** [comment]
Yes -- call NewClient, then replace the embedded `http.Client` with your client with a custom transport. Please note though that you need to do that before calling other functions on the client, or you can encounter races.
