### ISSUE TITLE
No support for request.WithContext 

### ISSUE THREAD

**Issue by macnibblet** [hashicorp/go-retryablehttp#17]
Heya,

Lovely piece of code as usual, but one thing I find slightly annoying is that I cannot use `request.WithContext` since that returns the request struct from `net/http`. Any suggestions on how to get around this?

**Comment by gir** [comment]
Would this work?

```go
r, err := retryablehttp.NewRequest("GET", "http://foo", nil)
r.Response = r.WithContext(context.Background())
```

**Comment by macnibblet** [comment]
Aah, smart!

Btw you have a typo it should be 
```go
r, _ := retryablehttp.NewRequest("GET", "http://foo", nil)
r.Request = r.WithContext(context.Background())
```

**Comment by gir** [comment]
Thanks, updated the snippet.
