### ISSUE TITLE
Request with context

### ISSUE THREAD

**Issue by vbauerster** [hashicorp/go-retryablehttp#22]
Calling WithContext on wrapped [Request](https://godoc.org/github.com/hashicorp/go-retryablehttp#Request), would return *http.Request, so user cannot do:

```go
req, err := NewRequest(http.MethodGet, ts.URL, nil)
if err != nil { /* handle error */ }
ctx, cancel := context.WithCancel(req.Request.Context())
req = req.WithContext(ctx) // compile time error here
```

Also the lib would start retrying on context error, i.e. cancel called. Which is imo wrong. If user calls cancel, the intention is cancel, not retry.

**Comment by tkanos** [comment]
Hey dudes,

It's something that the community are waiting since April, when will it be released ?

**Comment by jefferai** [comment]
@tkanos When someone in the community fixes up a PR that doesn't have conflicts with `master`, or when someone at HashiCorp needs it and does it internally.
