### ISSUE TITLE
Disable DEBUG logs

### ISSUE THREAD

**Issue by angadn** [hashicorp/go-retryablehttp#31]
How do I disable the DEBUG log that pop for every request made?

**Comment by angadn** [comment]
I have set `client.Logger = nil`. Is this the recommended way?

**Comment by jefferai** [comment]
Yep!

**Comment by kevinburkemeter** [comment]
Another way to look at this question is why is the default setting to print DEBUG logs.

**Comment by ryanuber** [comment]
This library will write debug messages so that they are available to the logger implementation. Ultimately, it is up to the actual logger you use to decide whether or not DEBUG logs should be printed or not.

**Comment by encryptblockr** [comment]
> I have set `client.Logger = nil`. Is this the recommended way?

How do we combine multiple options together? We already have to add this on new line `retryClient.RetryMax = 10` and now another one `retryClient.Logger = nil`

how can we combine multiple options together?

**Comment by mohsenasm** [comment]
I saw this line in the code:
```go
Logger     interface{}  // Customer logger instance. Can be either Logger or LeveledLogger
```

So it seems we can use this interface for leveled logging:

```go
type LeveledLogger interface {
	Error(msg string, keysAndValues ...interface{})
	Info(msg string, keysAndValues ...interface{})
	Debug(msg string, keysAndValues ...interface{})
	Warn(msg string, keysAndValues ...interface{})
}
```
