### ISSUE TITLE
go-retryablehttp http.RoundTripper

### ISSUE THREAD

**Issue by mmatczuk** [hashicorp/go-retryablehttp#37]
Hi HashiCorp,
some 6 month ago I cloned your project and refactored Client to http.RoundTripper. The basic difference it that instead of 

```go
type Client struct {
	HTTPClient *http.Client // Internal HTTP client.
...
```

I'm using

```go
type Transport struct {
	next http.RoundTripper
...
```

The reason why I did that is because it's much easier to integrate that to existing code bases. You can also use it effectively as part of more complicated middleware chains.

The work can be enhanced to provide both options in the retryablehttp package. Would you be interested in such a patch?

Implementation idea: there would be both retryablehttp.Client and retryablehttp.Transport types and client would be using the transport when constructed [1]. Please let me know what do you think.

ps.
Thanks for sharing this cool library, I really enjoy working with your code!

[1] https://github.com/hashicorp/go-retryablehttp/blob/master/client.go#L261

**Comment by jefferai** [comment]
I never saw a PR for this come in, are you still planning on submitting one?

**Comment by jefferai** [comment]
Also to make sure I'm understanding the ask, you want https://golang.org/pkg/net/http/#RoundTripper to be satisfied by the Client?

**Comment by mmatczuk** [comment]
Hi @jefferai I see that you guys have implemented the vision in https://github.com/hashicorp/go-retryablehttp/pull/90. We have a different implementation that makes client a transport I like this one better. I'm closing this issue.
