### ISSUE TITLE
URL in logs / errors and better control of the logging

### ISSUE THREAD

**Issue by fantyz** [hashicorp/go-retryablehttp#41]
Hi,

I'm currently using this otherwise nice package to interact with 3rd party APIs, which force me to put its API keys into the actual URL. Since the package include the URL in both its logs as well as include them in the errors it return to leak the API keys into our logs - which is unfortunate.

Additionally the logging doesn't quite allow me to do what I need of it. It seems like the package attempt to do leveled logs, but not really?

We used leveled logs (`logrus`) and ideally I would like the failed HTTP requests to be logged at `WARN` level. However the current implementation either force me to have non-warn related logs (even prefixed with `debug` at `WARN` level, failed requests logged at `INFO` or `DEBUG` or loose the information around what cause requests to fail entirely.

As I don't see adding a dependency to any leveled logging packages out there as an option, I would suggest either:

1. Change the existing logger into a simple leveled logger interface defined in the package itself as well as provide helpers to make it as easy as possible (possibly also backwards compatible if that is a priority) to turn a `log.Logger` into one that implements this simple leveled logger.
2. Specify two distinct `log.Logger` loggers on `Client` (one used for errors and one used for everything else). Given most decent leveled loggers today offer a possibility to be used as a standard `log.Logger` at a given level, this then, in turn, allow the user to set these using a leveled logger that is fixed to a specific level (most leveled logging packages I've seen has basic support for this).

I was wondering whether I should remake a similar package or if you would be open to a PR that:

* Add a boolean field on `Client` that allow you to toggle whether to include the URL in errors/logs (with default behavior that keeps logs as is)
* Either makes its own simple leveled logging interface or add two different `log.Logger` fields to `Client`?

Best regards,
Kasper

**Comment by jefferai** [comment]
Is the API key in the actual path or in the query part of the URL? If it's in the query part we may just want to remove (or put behind a bool) whether the query is shown in logs. If it's in the actual path, I'd be opposed to any change here.

I don't think we should add a leveled logging interface. I don't have a better idea at the moment, as there are multiple issues here: the inflexibility of the current logger, what level it should even log at, if any, the many different types of loggers out there that people may want to use instead. I don't think the right way to go is to add two different Logger fields because the question then becomes, which Logger to use when, and what type should the second one be.

**Comment by fantyz** [comment]
It's part of the actual URL in both cases we currently have the issue. What cause you to oppose it? I get that the usefulness is reduced significantly if requests are done to multiple URLs as there is no easy way to differentiate, but the is not having any logs/errors at all..?
Maybe some kind of toggle level that allows you to set it to no url, url wo. query params or full url to increase the possible use cases?

Regarded having two loggers; Both would be regular standard `log.Logger`'s (ie. one named `InfoLogger` and `ErrorLogger`). If you don't care about levels you set both to the same `log.Logger` (I think I would add two setter functions; one that just takes one `log.Logger` and sets both and one that takes two `log.Logger`'s and set them differently to hide the complexity from people that don't want/need it.

**Comment by fantyz** [comment]
Realizing that the error problem is broader than just this package (changing the message of an error is easily possible without having to recreate a new error with the same (now filtered) message and thus loosing the original error (and any type that underlies it) in the process. I don't see any way to sort this out nicely, so instead, I'm not doing this filtering in the logging package instead.

This still leaves the non-leveled logging which will cause the "debug" messages to pop up as something bad in our log system.

How about just a debug-mode toggle that enables/disables the logging of the "debug" message that happens? That would allow me to only get the errors logged at an appropriate level and should have a very minimal impact on the package otherwise.

**Comment by fantyz** [comment]
I'm not sure how I missed #32 - this approach fixes the logging issues I have.
