### ISSUE TITLE
Can I set defaultClient configuration Transport -> TLSClientConfig?

### ISSUE THREAD

**Issue by dundich** [hashicorp/go-retryablehttp#51]
tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	return &http.Client{Transport: tr}

**Comment by dundich** [comment]
maybe factory with hook...

**Comment by jefferai** [comment]
After you define a Client in the library you can modify the underlying http.Client; see https://godoc.org/github.com/hashicorp/go-retryablehttp#Client
