### ISSUE TITLE
rework logger

### ISSUE THREAD

**Issue by moeryomenko** [hashicorp/go-retryablehttp#52]
In https://github.com/hashicorp/go-retryablehttp/pull/32 added custom logger, but it looks very strange, repeats twice the word `DEBUG`
```
{"level":"debug","time":"2019-04-04T16:45:01Z","message":"[DEBUG] POST https://`url`"}
```
https://github.com/hashicorp/go-retryablehttp/pull/49 here I suggested adding a level logger

**Comment by jefferai** [comment]
I'm not sure that output is incorrect. I can see both ways. If you think it should be changed I suggest filing an issue with the go-hclog repo.

**Comment by moeryomenko** [comment]
What do you mean?? 

if I set the level for the info logger, I will get:

```json
{"level":"info","message":"[DEBUG] POST http://`url`","time":"2019-04-05T08:29:27Z"}
```
You are not sure what is wrong? You indicate the level of the log in the [message](https://github.com/hashicorp/go-retryablehttp/blob/master/client.go#L372), do you think this is correct?

What about `go-hlog`, do you mean using it as default logger?

**Comment by kedare** [comment]
Yes this is wrong, as it always put logs as info level where it's actually debug or something else.
