### ISSUE TITLE
Close resp in a defer

### ISSUE THREAD

**Issue by sfro** [hashicorp/go-retryablehttp#54]
Why is the following not done in a defer as soon as the request has been made? Am I missing something?
https://github.com/hashicorp/go-retryablehttp/blob/master/client.go#L462

**Comment by jefferai** [comment]
Not sure. Are you seeing a problem?

**Comment by jefferai** [comment]
Note that resp.Body is closed in `drainBody`

**Comment by sfro** [comment]
I was just trying to understand the code. I guess here we could have a leak:
https://github.com/hashicorp/go-retryablehttp/blob/master/client.go#L425
But then I guess it's the callers responsibility to close the body?

**Comment by jefferai** [comment]
Correct..in the case we aren't retrying, we follow normal Go http semantics where the caller closes the body after reading.

**Comment by sfro** [comment]
Ok, then I understand the use case better. I'll close this issue.
