### ISSUE TITLE
Timeout backoff feature

### ISSUE THREAD

**Issue by NilsJPWerner** [hashicorp/go-retryablehttp#63]
It would be great to have a feature that allows timeouts to increase or change every retry. 

This could be integrated by having a `TimeoutBackoff` interface similar to the current `Backoff` option that allows users to create their own function to change the timeout after a failed attempt. If the request succeeds or runs out of retrys the timeout would be reset.

If people think this is a good idea, I can create the PR.

**Comment by ryanuber** [comment]
Hey @NilsJPWerner,

It sounds to me like the `Backoff` interface should already meet your needs. It allows specifying a custom function which returns the amount of time to wait before retrying. It also takes the `attemptNum` which will be incremented on each failed attempt, so you can use that to perform multiplication or whatever you need to do to increase the wait time.

If I've missed something, let me know, but I think this is achievable in the current implementation!

**Comment by ryanuber** [comment]
I'm actually going to close this out for now but let me know if you have other thoughts or suggestions that I missed.
