### ISSUE TITLE
Use of HTTPClient.CloseIdleConnections breaks compatibility with Go < v1.12

### ISSUE THREAD

**Issue by bvisness** [hashicorp/go-retryablehttp#66]
The [recent addition](https://github.com/hashicorp/go-retryablehttp/commit/7ccf08b78e9d23820c0f0f97bcf4cab14f72b454) of `HTTPClient.CloseIdleConnections` breaks compatibility with versions of Go less than 1.12, since `CloseIdleConnections` was [added in v1.12](https://golang.org/doc/go1.12#net/http).

_Originally posted by @bodhi in https://github.com/hashicorp/go-retryablehttp/pull/57_

**Comment by jefferai** [comment]
I think for the moment users of previous versions of Go will simply have to use previous versions of the library.

Once Go 1.13 comes out only it and Go 1.12 will be supported by upstream anyways.

**Comment by jefferai** [comment]
Now that Go 1.13 is out the Go team only supports 1.13 and 1.12, so it is reasonable to depend on it.

**Comment by bvisness** [comment]
Ok, but version 0.6.0 of this package is compatible with older versions of Go, while versions 0.6.1 and onward are not, so you may want to clean up the version tags. You also may want to clarify that this repo and vault itself are only compatible with Go 1.12 and up.

**Comment by jefferai** [comment]
I can add that info to the README. What do you mean by "clean up the version tags"? It's 0.x so there are no rules.

**Comment by bvisness** [comment]
Ah, fair point. Thanks for adding the clarification.
