### ISSUE TITLE
Remove printing req.Method and req.Url

### ISSUE THREAD

**Issue by sahith-narahari** [hashicorp/go-retryablehttp#68]
While using retryablehttp in my project where multiple requests are involved,fills my entire log with request urls and methods.I thing this print(on line 524) of client.go can be removed.This shouldn't be a problem as users of this package can print their request info before or after the request is done.

**Comment by ryanuber** [comment]
Hi @sahith-narahari,

I think we should keep this in place. The logs aren't useful without the context of the URL being requested and the method. It's true you can log before and after, but in the case of highly concurrent applications this does little to provide the necessary context, especially when multiple requests are in flight simultaneously.

Thanks for reporting this anyways!
