### ISSUE TITLE
HTTP Request error should be propagated to the caller

### ISSUE THREAD

**Issue by theckman** [hashicorp/go-retryablehttp#69]
Hello,

I'm working to add retryablehttp to a CLi I'm building for something, and noticed an interesting change in error messages as a result of doing that. Specifically when the `Do()` method exceeds its number of retries, the error it returns does not include the original error that was encountered:

https://github.com/hashicorp/go-retryablehttp/blob/46f7ba56794607f00b2e4797b3090b76dff6791e/client.go#L556-L557

So if there was a connection reset error causing it, versus an HTTP 500, the error doesn't provide that context to the consumer.

You do provide an `ErrorHandler`, but with what you've provided to that handler it's impossible to create an error string that is identical to the one above. This is because the `Do()` method relies on the `*http.Request` being in-scope to generate the retries exceeded error string, but that's not passed to `ErrorHandler`.

I'm interested in seeing whether: 

1. We can enhance that line of code above to also include the original error string in the message.
2. The `ErrorHandler` can be updated to receive an `*http.Request` so that we can create an error identical to that of `Do()`.

**Comment by dudududi** [comment]
Hi, any update on this? I can see that PR has some conflicts, any chance to have it merged & released? The lack of possibility to examine original error is really annoying...

**Comment by theckman** [comment]
@dudududi I just pushed an update commit which should have addressed the feedback in that PR. Hopefully they have some spare time to review it.

**Comment by theckman** [comment]
PR #70 has a merge approve on it, but still waiting for the merge itself.
