### ISSUE TITLE
http.Client compatible NewHTTPClient?

### ISSUE THREAD

**Issue by StevenACoffman** [hashicorp/go-retryablehttp#77]
Hello! I like your functionality, but I'm in a situation where I need to adhere to the http.Client api exactly, and the `Do()` signature is not `func (c *Client) Do(req *http.Request) (*http.Response, error)`.

Lots of enhanced/replacement libraries seem to implement the old api exactly so you can just swap out an import (pkg/errors vs. stdlib errors for instance). As a workaround, a wrapper is possible:
```
type RetryingHTTPClient struct {
    client *retryablehttp.Client
}

func (c *RetryingHTTPClient) Do(req *http.Request) (*http.Response, error) {
    wrappedReq, err := retryablehttp.FromRequest(req)
    if err != nil {
        return nil, err
    }

    return c.client.Do(wrappedReq)
}
```
Is there any openness to a PR adding a method like `NewHTTPClient()` that would return a client that conformed to something like `func (c *RetryingHTTPClient) Do(req *http.Request) (*http.Response, error)`? 
```
// HTTPDoer is an interface for the one method of http.Client that is used by RetryingHTTPClient
type HTTPDoer interface {
	Do(*http.Request) (*http.Response, error)
}
```

**Comment by ryanuber** [comment]
FYI, #90 was merged and tagged yesterday to satisfy these use cases 👍
