### ISSUE TITLE
Client configurable through constructor

### ISSUE THREAD

**Issue by tgropper** [hashicorp/go-retryablehttp#79]
Hi! I've just added [here](https://github.com/fravega/go-retryablehttp/tree/feature/constuctor-options) the `options pattern` so it'll be nicer to configure the `Client` with custom settings.  
If you see it as a feature to be added to the library, I'll send the PR.

Thanks!

**Comment by ryanuber** [comment]
Hey @tgropper! I think I prefer to keep the retryablehttp interface minimal, and lean on core features of the language (public struct fields) to provide configuration at this time. Thanks!
