### ISSUE TITLE
Adding TLS transport in Client

### ISSUE THREAD

**Issue by kpiyush17** [hashicorp/go-retryablehttp#80]
I want to add TLSClientConfig in http Client. 
```
transport := &http.Transport{TLSClientConfig: tlsConfig}
```

Is there a way to send tls config thorugh `retryablehttp`?

Thanks

**Comment by jefferai** [comment]
Sure, simply replace the HTTPClient variable in the Client struct that you get back from https://godoc.org/github.com/hashicorp/go-retryablehttp#NewClient

**Comment by seanw2020** [comment]
Example:

```
		client := retryablehttp.NewClient()
		client.HTTPClient = &http.Client{
			Transport: &http.Transport{
				TLSClientConfig: tlsConfig,
			},
		}
```
