### ISSUE TITLE
Library closes all connections, makes reuse impossible

### ISSUE THREAD

**Issue by Richtermeister** [hashicorp/go-retryablehttp#85]
As a followup to: https://github.com/hashicorp/go-retryablehttp/pull/57#pullrequestreview-234625048

If I'm reading this correctly, the library currently seems to close all happy-case connections, which makes it unsuitable for use in a micro-service architecture where many requests go to the same few hosts. I'm currently observing this behavior in one of my services.
This is not just a connection-time issue, but in my case the closed requests eat up available sockets in TIME_WAIT state to the point of machine failure.

@jefferai Could you please revisit this review request above with this consideration in mind?
I'm happy to PR this is you concur it's an issue.

**Comment by jefferai** [comment]
I won't be revisiting it, but feel free to propose a way forward in a PR. Maybe a config value or something.

**Comment by Richtermeister** [comment]
Thank you for responding so quickly.

I guess what I don't understand is why this library should close any connections in any case. If we're retrying a request internally it's beneficial to reuse a connection, and if the request succeeds, it's probably fair to say that the user might issue another request to the same host. 
If the user wants to suppress this behavior (avoid reusing connections), this can already be done easily by overriding the `Transport.DisableKeepAlives` setting.

Thank you for helping me understand this better.

**Comment by jefferai** [comment]
It does it because #57 addressed #44 and we didn't really have any known use cases wanting a different approach. So it was a way to keep the same behavior but allow connection reuse for retries.

As I said, feel free to propose an alternative. Maybe that's just removing this line. Dunno. It's a behavior change but may be the right thing to do.

**Comment by jefferai** [comment]
Oh one other thing likely relevant: each request uses a clean connection pool so if there are a ton of connections and they are sticking around waiting to time out you could end up with lots and lots of open fds which will bork some systems. Another reason to make it configurable.

**Comment by Richtermeister** [comment]
This is actually exactly the issue I'm facing *because* of the connection closing. Each connection that is closed it goes into `TIME_WAIT` state on the host and becomes unusable for 30-120 seconds (depending on host config). All new requests that are issued in the meantime add to the fds count. Allowing reuse avoids this.

Thank you for your feedback, I really appreciate it. I'll send a PR soon. Have a nice evening.

**Comment by codeperfector** [comment]
@jefferai Why was this issue closed? I am currently facing the same issue as @Richtermeister - the library closes all idle connections and that makes reuse impossible for my subsequent requests that are going to the same host. I currently have this workaround for it:

```
type myHttpTransport struct {
	*http.Transport
}

func newMyHttpTransport(transport *http.Transport) *myHttpTransport {
	return &myHttpTransport{transport}
}

func (c *myHttpTransport) CloseIdleConnections() {
	// Do nothing, do not close idle connections, let them timeout instead.
}


client := retryhttp.NewClient()

// Must be a transport so we can override specific values
transport := client.HTTPClient.Transport.(*http.Transport)

// wrap this transport with our own to avoid closing idle connections for re-use
client.HTTPClient.Transport = newMyHttpTransport(transport)

```

I would prefer adding a configurable option. Please Let me know if this is still a valid issue that I can address with a PR or if any PRs are out there addressing this issue that I may have missed. 

Thanks for all the good work here!

**Comment by jefferai** [comment]
@codeperfector I closed it because the OP's request was specifically for me to revisit the previous change and modify the code to address this. As I said, I will not be doing that, but I'm happy to look at PRs that do.
