### ISSUE TITLE
Setting timeouts

### ISSUE THREAD

**Issue by canni** [hashicorp/go-retryablehttp#96]
As far as I can see in current API there's no way to set a request timeout, neither per request nor per client.

In a bare http client I can set client request timeout using `client.Timeout` Retrying client does not expose `hashiClient` struct member so I can't set this per client. And I'm also unaware on how can I set per request timeout?

**Comment by canni** [comment]
Uh, sorry I found how to do this now (facepalm)

**Comment by slinkydeveloper** [comment]
> And I'm also unaware on how can I set per request timeout?

Hey @canni did you found out how to do that? Can you please share? :smile:

**Comment by cuducos** [comment]
I'm sorry, @canni, but I'm gonna expose your secret 💜 

```go
retryClient := retryablehttp.NewClient()
retryClient.HTTPClient.Timeout = time.Minute * 3
```

**Comment by jdemeyer** [comment]
Also got here by searching for "go-retryablehttp timeout", might be good to officially document this somewhere.
